# Generated by Django 4.1.1 on 2022-10-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_alter_dealership_group'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='associatedcategory',
            unique_together={('dealership', 'category')},
        ),
    ]
