# Generated by Django 4.1.1 on 2022-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_associatedcategory_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="associatedcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is_active"),
        ),
    ]
