# Generated by Django 4.1.1 on 2022-10-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.dealershipgroup', verbose_name='Group'),
        ),
    ]
