# Generated by Django 4.1.1 on 2022-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0007_alter_dealership_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
