# Generated by Django 4.1.1 on 2022-11-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0006_alter_dealership_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='dealership.dealership', verbose_name='Dealership'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
